[program:omnivis_ai_platform]
command=/opt/vllm-ai-platform/native/platform-venv/bin/supervisord -n -c /opt/vllm-ai-platform/native/supervisord.conf
directory=/opt/vllm-ai-platform
user=root
priority=50
autostart=true
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=45
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
